### ISSUE TITLE
[Bug] Drag+drop images doesn't work

### ISSUE THREAD

**Issue by eartharoid** [mue/mue#762]
### Description

An error is thrown

### Version

7.0.0

### What browser(s) are you seeing the problem on?

Mozilla Firefox, Microsoft Edge

### Relevant log output

```shell
# Firefox

Uncaught (in promise) TypeError: s.target is undefined
    customBackground https://demo.muetab.com/assets/Settings-BiDrSimu.js:2
    ondrop https://demo.muetab.com/assets/Settings-BiDrSimu.js:2
    ondrop https://demo.muetab.com/assets/Settings-BiDrSimu.js:2


# Edge

Settings-BiDrSimu.js:2 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'result')
    at Tt.customBackground (Settings-BiDrSimu.js:2:39585)
    at Settings-BiDrSimu.js:2:41485
customBackground	@	Settings-BiDrSimu.js:2
(anonymous)	@	Settings-BiDrSimu.js:2
FileReader (async)		
(anonymous)	@	vendor-BFOCiyLt.js:47
h	@	vendor-BFOCiyLt.js:47
(anonymous)	@	Settings-BiDrSimu.js:2
Promise.then (async)		
s.ondrop	@	Settings-BiDrSimu.js:2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidcralph** [comment]
Fixed in #762, thanks for your report!
